export const GET_ALL_USER_START = "GET_ALL_USER_START";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const REGISTER_USER = "REGISTER_USER";
